#!/usr/bin/env bash
#install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo service start nginx
sudo echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sudo service restart nginx
