#!/usr/bin/env bash
#install nginx
apt-get update -y
apt-get install -y nginx
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sed -i  s/"\# pass".*/"location \/redirect_me \{\n\t\treturn 301 https\:\/\/www.youtube.com\/watch?v=nQAdYNB8nXU\;\n\t\}"/ /etc/nginx/sites-enabled/default
service nginx restart
