#!/usr/bin/env bash
#install nginx
apt-get update -y
apt-get install -y nginx
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sed -i  s/"\# pass".*/"location \/redirect_me \{\n\t\treturn 301 https\:\/\/www.youtube.com\/watch?v=nQAdYNB8nXU\;\n\t\}"/ /etc/nginx/sites-enabled/default
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i s/"\# include snip".*/"error_page 404 \/404.html;\n\tlocation  \/404.html \{\n\t\tinternal\;\n\t\}"/ /etc/nginx/sites-enabled/default
sed -i s/"\tlocation\ \/\ ".*/"\tlocation \/ \{\n\t\tadd_header X-Served-By \"$HOSTNAME\"\;"/ /etc/nginx/sites-enabled/default
sudo service nginx restart
