#!/bin/bash
# manage process

start() {
    ./manage_my_process &
    echo "manage_my_process started"   
    echo "$$" > /var/run/my_process.pid
}

stop () {
    echo "manage_my_process stopped"
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
}

restart () {
    echo "manage_my_process restarted"
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    echo "$$" > /var/run/my_process.pid
}

##case statement to be used to call functions##
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
*)
echo $"Usage: $0 {start|stop|restart}"
exit 5
esac
exit $?
