#!/usr/bin/env bash
# read and parse a file

while read -r LINE
do

	echo "The user $(echo "$LINE" | cut -f 1 -d ":") is part of the $(echo "$LINE" | cut -f 4 -d ":") gang, lives in $(echo "$LINE" | cut -f 6 -d ":") and rides $(echo "$LINE" | cut -f 7 -d ":"). $(echo "$LINE" | cut -f 3 -d ":")'s place is protected by the passcode $(echo "$LINE" | cut -f 2 -d ":"), more info about the user here: $(echo "$LINE" | cut -f 5 -d ":")"

done < /etc/passwd
