#!/usr/bin/env bash
# Information about a file


if [[ $(file holbertonschool | grep cannot | wc -l) -eq 0 ]]
then
	echo "holbertonschool file exists"
	if [[ $(file holbertonschool | grep empty | wc -l) -eq 1 ]]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [[ $(find . -name "holbertonschool" -type f | wc -l) -eq 1 ]]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
