#!/bin/bash
# Redirect 8080 to 80

ufw status
ufw allow 22
ufw allow 443
ufw allow 80
ufw allow 8080
echo -e "*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT" > /etc/ufw/before.rules1
cat /etc/ufw/before.rules >> /etc/ufw/before.rules1
mv /etc/ufw/before.rules1 /etc/ufw/before.rules
ufw disable
ufw enable
