#!/usr/bin/env bash
# answer

cp /etc/hosts ~/hosts.new
sed -i 's/localhost//'  ~/hosts.new
echo '127.0.0.2	localhost' >> ~/hosts.new
sed -i 's/facebook.com//'  ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
sed -E -i '/^([0-9]{1,3}\.){3}[0-9]{1,3}[\t\ ]*$/d' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
