#!/usr/bin/env bash
# repair nginx
sed -i 's/\#user\ www-data\;/user\ nginx\;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
service apache2 stop
service nginx start
